//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCorrespondenceEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentLog
    {
        public int TransactionID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string LOB { get; set; }
        public string LetterName { get; set; }
        public string Payload { get; set; }
        public string PolicyNumber { get; set; }
        public string Environment { get; set; }
        public string BaseState { get; set; }
        public string ClaimNumber { get; set; }
        public string QuoteNumber { get; set; }
        public string ProducerCode { get; set; }
    }
}
