//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCorrespondenceEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentControl
    {
        public int DocumentControlId { get; set; }
        public int DocumentId { get; set; }
        public int ControlId { get; set; }
        public int ControlOrder { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    
        public virtual Control Control { get; set; }
        public virtual Document Document { get; set; }
    }
}
