//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCorrespondenceEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLogId { get; set; }
        public string ErrorMessage { get; set; }
        public string InputXML { get; set; }
        public string OutputXML { get; set; }
        public string PolicyNumber { get; set; }
        public string ClaimNumber { get; set; }
        public string QuoteNumber { get; set; }
        public string Lob { get; set; }
        public string ErrorCode { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LetterName { get; set; }
        public string ProducerCode { get; set; }
        public string Environment { get; set; }
        public string State { get; set; }
    }
}
