//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCorrespondenceEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupItem
    {
        public int LookupItemID { get; set; }
        public string LookupItemCode { get; set; }
        public string LookupItemValue { get; set; }
        public int LookupTypeID { get; set; }
        public int LookupItemOrder { get; set; }
    
        public virtual LookupType LookupType { get; set; }
    }
}
