//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveCorrespondenceEditor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebServices
    {
        public int WebServicesId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string LOB { get; set; }
        public string Environment { get; set; }
        public string URLType { get; set; }
        public string URLInfo { get; set; }
        public string URL { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
